services:

  worker:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis-server:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-server:6379/0
      - TZ=Asia/Seoul
    command: python -m celery -A app.core.celery_app worker --loglevel=info --pool=solo
    networks:
      - shared-app-network

  flower:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis-server:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-server:6379/0
      - TZ=Asia/Seoul
    command: python -m celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    networks:
      - shared-app-network

networks:
  shared-app-network:
    external: true
