
services:
  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - HOST=0.0.0.0
      - PORT=5050
      - WORKERS=4
      - DATABASE_URL=postgresql+asyncpg://sa:1@localhost:15432/postgres
      - REDIS_URL=redis://redis:6379/0
      - TZ=UTC
    networks:
      - app-network

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=UTC
    command: python -m celery -A app.core.celery_app worker --loglevel=info
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - TZ=UTC
    networks:
      - app-network

  flower:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=UTC
    command: python -m celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge