version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.cpu} # 기본 CPU, GPU 사용 시 환경변수 설정
    container_name: fastapi-app
    ports:
      - "35050:5050"
    environment:
      - TZ=Asia/Seoul
      - HOST=0.0.0.0
      - PORT=5050
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    external: true
