[tool.poetry]
name = "study"
version = "0.1.0"
description = "FastAPI-based LLM service with Kafka message processing"
authors = ["albin <ybkim@aipim.io>"]
readme = "README.md"
package-mode = false

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu118" # <-- 이 부분을 운영 환경의 CUDA 버전에 맞게 수정
priority = "explicit"

[tool.poetry.dependencies]
python = "~3.12"
fastapi = "0.104.1"
uvicorn = {extras = ["standard"], version = "0.24.0"}
# 개발 환경 (CPU 전용) - macOS 호환 버전
torch = "^2.2.0"
torchvision = "^0.17.0"
transformers = "^4.40.0"
huggingface-hub = "^0.23.0"
pydantic = "2.11.9"
pydantic-settings = "2.1.0"
aiokafka = "^0.10.0"
numpy = "<2.0.0"
gunicorn = "^21.2.0"
celery = "^5.5.3"
redis = "^5.0.0"
flower = "^2.0.1"
sqlalchemy = "^2.0.43"
asyncpg = "^0.30.0"
alembic = "^1.16.5"
greenlet = "^3.2.4"
psycopg2-binary = "^2.9.10"
sqlacodegen = ">=3.0,<3.1"
psycopg = "^3.2.10"
httpx = "^0.28.1"
psutil = "^7.0.0"
langchain = "^0.3.0"
langchain-ollama = "^0.3.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
pre-commit = "^3.0.0"
aiosqlite = "^0.21.0"

# 운영 환경 전용 의존성 (선택적)
[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
# 운영 환경 (GPU 전용) - 별도 설치 필요
# torch = { version = "^2.2.0", source = "pytorch-cuda" }
# torchvision = { version = "^0.17.0", source = "pytorch-cuda" }
sentry-sdk = "^1.0.0"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "--strict-markers",
    "--verbose",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



# [tool.poetry]
# name = "study"
# version = "0.1.0"
# description = "FastAPI-based LLM service with Kafka message processing"
# authors = ["albin <ybkim@aipim.io>"]
# readme = "README.md"
# package-mode = false

# [[tool.poetry.source]]
# name = "pytorch-cpu"
# url = "https://download.pytorch.org/whl/cpu"
# priority = "explicit"

# [tool.poetry.dependencies]
# python = "~3.12"
# fastapi = "0.104.1"
# uvicorn = {extras = ["standard"], version = "0.24.0"}
# # torch = "^2.1.0"  # pip로 별도 설치
# transformers = "^4.40.0"
# huggingface-hub = "^0.23.0"
# pydantic = "2.5.0"
# pydantic-settings = "2.1.0"
# aiokafka = "^0.10.0"
# numpy = "<2.0.0"
# gunicorn = "^21.2.0"
# celery = "^5.5.3"
# redis = "^5.0.0"
# flower = "^2.0.1"
# sqlalchemy = "^2.0.43"
# asyncpg = "^0.30.0"
# alembic = "^1.16.5"
# greenlet = "^3.2.4"
# psycopg2-binary = "^2.9.10"
# sqlacodegen = ">=3.0,<3.1"
# psycopg = "^3.2.10"
# httpx = "^0.28.1"
# psutil = "^7.0.0"

# [tool.poetry.group.dev.dependencies]
# pytest = "^7.0.0"
# pytest-asyncio = "^0.21.0"
# black = "^23.0.0"
# flake8 = "^6.0.0"
# mypy = "^1.0.0"
# pre-commit = "^3.0.0"
# aiosqlite = "^0.21.0"

# [tool.black]
# line-length = 88
# target-version = ['py311']
# include = '\.pyi?$'

# [tool.mypy]
# python_version = "3.12"
# warn_return_any = true
# warn_unused_configs = true

# [tool.pytest.ini_options]
# testpaths = ["tests"]
# python_files = ["test_*.py"]
# addopts = [
#     "--strict-markers",
#     "--verbose",
# ]

# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"