[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "api-server"
version = "0.1.0"
description = "FastAPI-based API server"
requires-python = ">=3.12"
dependencies = [
    "shared", # 내부 공통 패키지 (fastapi, sqlalchemy, pydantic, pydantic-settings 포함)
    "uvicorn[standard]>=0.27.0",
    "alembic>=1.16.5",
    "httpx>=0.28.1",
    "python-dotenv>=1.0.0",
    "python-json-logger>=2.0.7",
    "python-multipart>=0.0.6",
    "psutil>=7.0.0",
    "levenshtein>=0.27.1",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]
