services:
  redis:
    container_name: redis-server
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - shared-app-network
    restart: unless-stopped

  postgres:
    container_name: postgres-server
    image: postgres:15-alpine
    environment:
      PGTZ: Asia/Seoul
      POSTGRES_DB: study_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: "1"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - /Users/aipim/yb/python/fastapi_celery_study/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d study_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-app-network

  prometheus:
    image: prom/prometheus:v2.47.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - node-exporter
      # - dcgm-exporter

  # gpu 필요
  # dcgm-exporter:
  #   image: nvcr.io/nvidia/k8s/dcgm-exporter:3.2.3-3.1.6-ubuntu20.04
  #   container_name: dcgm-exporter
  #   # --gpus all는 호스트의 모든 GPU에 대한 접근을 허용합니다.
  #   # 특정 GPU만 사용하려면 '--gpus "device=0,1"' 와 같이 지정합니다.
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   environment:
  #     - DCGM_EXPORTER_NO_HOSTNAME=1
  #   ports:
  #     - "9400:9400"
  #   restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.6.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /dev/nvidia0:/dev/nvidia0 # Add this line for each GPU
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/rootfs"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /Users/aipim/yb/python/fastapi_celery_study/grafana-data:/var/lib/grafana
    restart: unless-stopped

networks:
  shared-app-network:
    external: true
