"""Add task_info tables

Revision ID: 0a8de832e7fb
Revises: bd0d3d982d30
Create Date: 2025-09-02 15:54:28.985084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8de832e7fb'
down_revision: Union[str, Sequence[str], None] = 'bd0d3d982d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('date_done', sa.String(length=255), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('traceback', sa.String(length=255), nullable=False),
    sa.Column('task_time', sa.DateTime(timezone=True), nullable=False, comment='생성 시간'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_info_id'), 'task_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_info_id'), table_name='task_info')
    op.drop_table('task_info')
    # ### end Alembic commands ###
