"""Add chain support to TaskInfo

Revision ID: 1b7a57cce659
Revises: 0d55c979103c
Create Date: 2025-09-04 11:32:35.658166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7a57cce659'
down_revision: Union[str, Sequence[str], None] = '0d55c979103c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('root_task_id', sa.String(), nullable=True))
    op.add_column('task_info', sa.Column('parent_task_id', sa.String(), nullable=True))
    op.add_column('task_info', sa.Column('chain_id', sa.String(), nullable=True))
    op.add_column('task_info', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('task_info', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('task_info', sa.Column('chain_position', sa.Integer(), nullable=True))
    op.add_column('task_info', sa.Column('chain_total', sa.Integer(), nullable=True))
    op.add_column('task_info', sa.Column('chain_remaining', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_task_info_chain_id'), 'task_info', ['chain_id'], unique=False)
    op.create_index(op.f('ix_task_info_correlation_id'), 'task_info', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_task_info_group_id'), 'task_info', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_info_parent_task_id'), 'task_info', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_task_info_root_task_id'), 'task_info', ['root_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_info_root_task_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_parent_task_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_group_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_correlation_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_chain_id'), table_name='task_info')
    op.drop_column('task_info', 'chain_remaining')
    op.drop_column('task_info', 'chain_total')
    op.drop_column('task_info', 'chain_position')
    op.drop_column('task_info', 'correlation_id')
    op.drop_column('task_info', 'group_id')
    op.drop_column('task_info', 'chain_id')
    op.drop_column('task_info', 'parent_task_id')
    op.drop_column('task_info', 'root_task_id')
    # ### end Alembic commands ###
