"""restructure_taskinfo_for_pipeline_compatibility

Revision ID: 332e07041279
Revises: d1a6d31a7b5b
Create Date: 2025-09-05 09:37:48.345010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '332e07041279'
down_revision: Union[str, Sequence[str], None] = 'd1a6d31a7b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('step', sa.Integer(), nullable=True, comment='현재 태스크의 단계 번호'))
    op.add_column('task_info', sa.Column('ready', sa.Boolean(), nullable=True, default=False, comment='태스크 준비 상태'))
    op.add_column('task_info', sa.Column('progress', sa.Integer(), nullable=True, default=0, comment='진행률 (0-100)'))
    op.alter_column('task_info', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Celery 태스크 ID')
    op.alter_column('task_info', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='태스크 상태')
    op.alter_column('task_info', 'task_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='태스크 이름')
    op.drop_index(op.f('ix_task_info_chain_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_correlation_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_group_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_parent_task_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_root_task_id'), table_name='task_info')
    op.drop_column('task_info', 'chain_total')
    op.drop_column('task_info', 'kwargs')
    op.drop_column('task_info', 'completed_time')
    op.drop_column('task_info', 'correlation_id')
    op.drop_column('task_info', 'chain_id')
    op.drop_column('task_info', 'root_task_id')
    op.drop_column('task_info', 'chain_remaining')
    op.drop_column('task_info', 'error_message')
    op.drop_column('task_info', 'args')
    op.drop_column('task_info', 'retry_count')
    op.drop_column('task_info', 'parent_task_id')
    op.drop_column('task_info', 'group_id')
    op.drop_column('task_info', 'chain_position')
    op.drop_column('task_info', 'task_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('task_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='태스크 시작 시간'))
    op.add_column('task_info', sa.Column('chain_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('parent_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='재시도 횟수'))
    op.add_column('task_info', sa.Column('args', sa.TEXT(), autoincrement=False, nullable=True, comment='태스크 인자'))
    op.add_column('task_info', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='에러 메시지'))
    op.add_column('task_info', sa.Column('chain_remaining', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('root_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('chain_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('correlation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('completed_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='태스크 완료 시간'))
    op.add_column('task_info', sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=True, comment='태스크 키워드 인자'))
    op.add_column('task_info', sa.Column('chain_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_task_info_root_task_id'), 'task_info', ['root_task_id'], unique=False)
    op.create_index(op.f('ix_task_info_parent_task_id'), 'task_info', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_task_info_group_id'), 'task_info', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_info_correlation_id'), 'task_info', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_task_info_chain_id'), 'task_info', ['chain_id'], unique=False)
    op.alter_column('task_info', 'task_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='태스크 이름')
    op.alter_column('task_info', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='태스크 상태')
    op.alter_column('task_info', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Celery 태스크 ID')
    op.drop_column('task_info', 'progress')
    op.drop_column('task_info', 'ready')
    op.drop_column('task_info', 'step')
    # ### end Alembic commands ###
