"""update_base_model_timezone_to_seoul

Revision ID: 3b6a748cd127
Revises: c3dcf3277fd2
Create Date: 2025-09-05 11:20:02.909763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6a748cd127'
down_revision: Union[str, Sequence[str], None] = 'c3dcf3277fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (서울)',
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (서울)',
               existing_comment='수정 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (서울)',
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (서울)',
               existing_comment='수정 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (서울)',
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (서울)',
               existing_comment='수정 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_comment='수정 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_comment='생성 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_comment='수정 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_comment='생성 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간',
               existing_comment='수정 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간',
               existing_comment='생성 시간 (서울)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
