"""add_pipeline_id_to_taskinfo

Revision ID: 638eff659154
Revises: d00c4246607d
Create Date: 2025-09-05 09:45:44.704351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638eff659154'
down_revision: Union[str, Sequence[str], None] = 'd00c4246607d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('pipeline_id', sa.String(length=255), nullable=True, comment='파이프라인 ID'))
    op.create_index(op.f('ix_task_info_pipeline_id'), 'task_info', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_info_pipeline_id'), table_name='task_info')
    op.drop_column('task_info', 'pipeline_id')
    # ### end Alembic commands ###
