"""sync all tables with Base metadata

Revision ID: 8b173d77dbb2
Revises: 0a8de832e7fb
Create Date: 2025-09-02 15:56:20.216511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b173d77dbb2'
down_revision: Union[str, Sequence[str], None] = '0a8de832e7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
