"""새로운 기능 추가

Revision ID: b51d598833eb
Revises: 321e82a5cbcf
Create Date: 2025-09-11 13:35:59.390322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51d598833eb'
down_revision: Union[str, Sequence[str], None] = '321e82a5cbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chain_executions', 'chain_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_comment='체인 고유 ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chain_executions', 'chain_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_comment='체인 고유 ID',
               existing_nullable=False)
    # ### end Alembic commands ###
