"""새로운 기능 추가

Revision ID: d1a6d31a7b5b
Revises: 1b7a57cce659
Create Date: 2025-09-04 14:18:38.620109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1a6d31a7b5b'
down_revision: Union[str, Sequence[str], None] = '1b7a57cce659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_info_chain_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_correlation_id'), table_name='task_info')
    op.drop_index(op.f('ix_task_info_group_id'), table_name='task_info')
    op.drop_column('task_info', 'correlation_id')
    op.drop_column('task_info', 'chain_id')
    op.drop_column('task_info', 'chain_position')
    op.drop_column('task_info', 'chain_remaining')
    op.drop_column('task_info', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('chain_remaining', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('chain_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('chain_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task_info', sa.Column('correlation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_task_info_group_id'), 'task_info', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_info_correlation_id'), 'task_info', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_task_info_chain_id'), 'task_info', ['chain_id'], unique=False)
    # ### end Alembic commands ###
