"""새로운 기능 추가

Revision ID: f9bd8b69b1e4
Revises: b51d598833eb
Create Date: 2025-09-11 13:37:53.996195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bd8b69b1e4'
down_revision: Union[str, Sequence[str], None] = 'b51d598833eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chain_executions', 'chain_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='체인 고유 ID')
    op.drop_index(op.f('ix_chain_executions_chain_id'), table_name='chain_executions')
    op.create_index(op.f('ix_chain_executions_chain_id'), 'chain_executions', ['chain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_executions_chain_id'), table_name='chain_executions')
    op.create_index(op.f('ix_chain_executions_chain_id'), 'chain_executions', ['chain_id'], unique=True)
    op.alter_column('chain_executions', 'chain_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='체인 고유 ID')
    # ### end Alembic commands ###
