"""taskInfo delete column

Revision ID: f9f3efe290cd
Revises: 3b6a748cd127
Create Date: 2025-09-05 11:28:42.257791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f3efe290cd'
down_revision: Union[str, Sequence[str], None] = '3b6a748cd127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_info', 'task_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='태스크 이름'))
    # ### end Alembic commands ###
