@baseUrl = http://localhost:5050

### 모델 서비스 - 사용 가능한 모델 조회
GET {{baseUrl}}/api/v1/ocr/languages

###

### 모델 서비스 - 예측 요청
# POST {{baseUrl}}/api/v1/model/predict
# Content-Type: application/json

# {
#   "server": "default",
#   "model": "llama3",
#   "prompt": "모델 서비스를 통한 테스트 요청입니다."
# }

###