@baseUrl = http://localhost:8000

### 모델 서비스 - 사용 가능한 모델 조회
GET {{baseUrl}}/api/v1/ocr/languages

###

###
GET {{baseUrl}}/api/v1/pipeline/history


###


###
GET {{baseUrl}}/api/v1/version


###

#  curl -X POST "http://localhost:5050/api/v1/ocr/extract/sync" \
#     -H "Content-Type: application/json" \
#     -d '{"image_path": "/Users/aipim/yb/python/models/images/page_0029.png"}'
    