@baseUrl = http://localhost:5050

### 모델 서비스 - 사용 가능한 모델 조회
GET {{baseUrl}}/api/v1/common/images


###

#  curl -X POST "http://localhost:5050/api/v1/ocr/extract/sync" \
#     -H "Content-Type: application/json" \
#     -d '{"image_path": "/Users/aipim/yb/python/models/images/page_0029.png"}'
    